version: "3.8"
services:
  postgres:
    container_name: postgres_container
    image: postgres
    hostname: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: "BookingHotel"
    ports:
      - 8001:5432
    volumes:
      - postgres:/data/postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

  # backend:
  #   restart: always
  #   build: ./backend
  #   stdin_open: true
  #   volumes:
  #     - ./backend:/usr/src/app
  #     - /usr/src/app/node_modules
  #   depends_on:
  #     - postgres
  #     - pgadmin
  #   ports:
  #     - 3000:3000
  #   command: /bin/sh -c "pnpm prisma migrate dev && pnpm prisma generate"
volumes:
  postgres:
  pgadmin:
